#!/usr/bin/env python3
"""Update the CalVer string in a file with today's date."""

import re
import shlex
import sys
from datetime import date
from pathlib import Path, PurePath
from subprocess import CalledProcessError, run


def git_add(pathspec: str) -> None:
    """Add file contents to the index.

    Args:
        pathspec (str): Files to add content from.

    """
    args = shlex.split(f"git add {pathspec}")
    try:
        run(args, capture_output=True, check=True)
    except CalledProcessError as e:
        print(e.stderr, file=sys.stderr)
        sys.exit(e.returncode)


def replace(file: str, pattern: str, replacement: str) -> bool:
    """Substitute a pattern in a file with a given replacement.

    Args:
        file (str): The file that will be operated on.
        pattern (str): The pattern that will be replaced.
        replacement (str): The substitute for the pattern.

    Returns:
        bool: False if there was an error updating the file, else True.

    """
    try:
        with open(file, "r+", newline="") as f:
            updated = re.sub(pattern, replacement, f.read())
            f.seek(0)
            f.write(updated)
            f.truncate()
    except OSError as e:
        name = PurePath(file).name
        print(f"error updating {name}: {str(e)}", file=sys.stderr)
        return False
    return True


def update_version(file: str) -> None:
    """Find the CalVer string in a file and replace it today's date.

    Args:
        file (str): The file that contains a CalVer string.

    See Also:
        https://calver.org/

    """
    pattern = r"\d{4}\.\d{1,2}\.\d{1,2}"
    today = date.today().strftime(r"%Y.%m.%d")
    if replace(file, pattern, today):
        git_add(file)


def main() -> None:
    p = Path(__file__)
    repo_dir = p.resolve().parents[1]
    module = repo_dir.stem
    update_version(repo_dir / module / "__init__.py")


if __name__ == "__main__":
    main()
